# Generated by Django 5.2.8 on 2025-12-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=50)),
                ('berat', models.FloatField()),
                ('harga', models.IntegerField()),
                ('status', models.CharField(choices=[('proses', 'Proses'), ('selesai', 'Selesai')], default='proses', max_length=20)),
            ],
        ),
    ]
